global using Xunit;
global using Authentication.MagicLink.Extensions;
global using Authentication.MagicLink.Interfaces;
global using Authentication.MagicLink.Models;
global using Authentication.MagicLink.Services;
global using MagicLinkSettings = Authentication.MagicLink.Settings.MagicLinkSettings;
global using Microsoft.Extensions.DependencyInjection;
global using FluentAssertions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Options;
